# Generated by Django 3.1.3 on 2020-11-29 18:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # nopep8
                ('name', models.CharField(default='', max_length=100)),
                ('slug', models.SlugField(blank=True, default='', max_length=100)),  # nopep8
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),  # nopep8
                ('data', models.JSONField()),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='prices.pricetype')),  # nopep8
            ],
            options={
                'abstract': False,
            },
        ),
    ]
