# Generated by Django 3.1.3 on 2020-11-29 18:28

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='data',
            field=models.JSONField(default=core.helpers.jsonfield_default_value),
        ),
    ]
