# Generated by Django 3.1.3 on 2020-11-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0003_auto_20201129_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='hash',
            field=models.CharField(default='', max_length=32),
        ),
    ]
