# Generated by Django 3.1.3 on 2020-11-30 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20201129_1507'),
        ('prices', '0004_price_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='trim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.trim'),
        ),
    ]
