# Generated by Django 3.1.3 on 2020-11-30 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0005_price_trim'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
