# Generated by Django 3.1.3 on 2020-11-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0006_price_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
