# Generated by Django 3.1.3 on 2020-11-28 14:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField(blank=True, default='')),
                ('year', models.CharField(default='', max_length=4)),
                ('make', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.make')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
