# Generated by Django 3.1.3 on 2020-11-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='foreign_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
