# Generated by Django 3.1.3 on 2020-11-28 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_model_foreign_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField(blank=True, default='', max_length=255)),
                ('nice_name', models.CharField(default='', max_length=255)),
                ('foreign_id', models.CharField(blank=True, default='', max_length=255)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.model')),
            ],
        ),
    ]
