# Generated by Django 3.1.3 on 2020-11-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_trim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trim',
            name='name',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='trim',
            name='nice_name',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='trim',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=400),
        ),
    ]
