# Generated by Django 3.1.3 on 2020-11-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20201129_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trim',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
